"""PDF export using fpdf2 for After Visit Summary generation."""

import os
import logging
from datetime import datetime

from fpdf import FPDF

from models.schemas import VisitRecord

logger = logging.getLogger(__name__)


class MedSiftPDF(FPDF):
    """Custom PDF class with MedSift AI branding."""

    def header(self):
        """Add header to each page."""
        self.set_font("Helvetica", "B", 14)
        self.cell(0, 10, "MedSift AI", align="L")
        self.ln(6)
        self.set_font("Helvetica", "", 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 5, "After Visit Summary", align="L")
        self.set_text_color(0, 0, 0)
        self.ln(8)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(5)

    def footer(self):
        """Add footer with page number."""
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}}", align="C")

    def section_title(self, title: str):
        """Add a section title."""
        self.set_font("Helvetica", "B", 12)
        self.set_fill_color(240, 240, 240)
        self.cell(0, 8, f"  {title}", fill=True)
        self.ln(10)
        self.set_font("Helvetica", "", 10)

    def safe_multi_cell(self, w, h, text, **kwargs):
        """multi_cell with x reset to left margin to prevent overflow."""
        self.set_x(self.l_margin)
        self.multi_cell(w, h, str(text or ""), **kwargs)

    def add_paragraph(self, text: str):
        """Add a paragraph of text."""
        self.set_font("Helvetica", "", 10)
        self.safe_multi_cell(0, 5, text)
        self.ln(3)

    def add_table_row(self, cells: list[str], widths: list[int], bold: bool = False):
        """Add a table row with text truncation to prevent overflow."""
        style = "B" if bold else ""
        self.set_font("Helvetica", style, 9)
        max_height = 5
        for cell_text, width in zip(cells, widths):
            # Truncate text to fit within cell width
            text = str(cell_text or "")
            while self.get_string_width(text) > width - 2 and len(text) > 0:
                text = text[:-1]
            if len(text) < len(str(cell_text or "")):
                text = text[:-2] + ".." if len(text) > 2 else text
            self.cell(width, max_height, text, border=1)
        self.ln(max_height)


def generate_after_visit_summary(
    visit_data: VisitRecord,
    output_path: str,
    include_soap: bool = False,
) -> str:
    """Generate an After Visit Summary PDF.

    Args:
        visit_data: Complete visit record.
        output_path: Path to save the PDF.
        include_soap: Whether to include SOAP note (clinician export).

    Returns:
        The output file path.
    """
    os.makedirs(os.path.dirname(output_path) if os.path.dirname(output_path) else ".", exist_ok=True)

    pdf = MedSiftPDF()
    pdf.alias_nb_pages()
    pdf.set_auto_page_break(auto=True, margin=20)

    # --- Page 1: Header & Disclaimer ---
    pdf.add_page()

    # Visit info
    pdf.set_font("Helvetica", "", 10)
    visit_date_str = visit_data.visit_date.isoformat() if visit_data.visit_date else "N/A"
    pdf.cell(0, 6, f"Visit Date: {visit_date_str}    |    Visit Type: {visit_data.visit_type or 'N/A'}")
    pdf.ln(10)

    # Disclaimer
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(180, 0, 0)
    pdf.safe_multi_cell(0, 4,
        "DISCLAIMER: This summary was generated by AI from a recorded conversation. "
        "Please verify all information with your healthcare provider. "
        "This document does not constitute medical advice."
    )
    pdf.set_text_color(0, 0, 0)
    pdf.ln(5)

    ps = visit_data.patient_summary
    if not ps:
        pdf.add_paragraph("No patient summary data available.")
        pdf.output(output_path)
        return output_path

    # --- Patient Letter ---
    pdf.section_title("Patient Letter")
    summary_text = ps.visit_summary or "No summary available."
    for paragraph in summary_text.split("\n\n"):
        paragraph = paragraph.strip()
        if paragraph:
            pdf.add_paragraph(paragraph)

    # --- Medications ---
    if ps.medications:
        pdf.section_title("Medications")
        widths = [38, 25, 30, 25, 72]
        pdf.add_table_row(["Medication", "Dose", "Frequency", "Duration", "Instructions"], widths, bold=True)
        for med in ps.medications:
            pdf.add_table_row(
                [med.name, med.dose, med.frequency, med.duration, med.instructions],
                widths,
            )
        pdf.ln(5)

    # --- Tests Ordered ---
    if ps.tests_ordered:
        pdf.section_title("Tests Ordered")
        widths = [50, 80, 60]
        pdf.add_table_row(["Test", "Instructions", "Timeline"], widths, bold=True)
        for test in ps.tests_ordered:
            pdf.add_table_row(
                [test.test_name, test.instructions, test.timeline],
                widths,
            )
        pdf.ln(5)

    # --- Follow-Up Plan ---
    if ps.follow_up_plan:
        pdf.section_title("Follow-Up Plan")
        for fu in ps.follow_up_plan:
            pdf.set_font("Helvetica", "", 10)
            pdf.safe_multi_cell(0, 5, f"[ ] {fu.action} - {fu.date_or_timeline}")
            pdf.ln(2)
        pdf.ln(3)

    # --- Lifestyle Recommendations ---
    if ps.lifestyle_recommendations:
        pdf.section_title("Lifestyle Recommendations")
        for rec in ps.lifestyle_recommendations:
            pdf.set_font("Helvetica", "B", 10)
            pdf.safe_multi_cell(0, 5, rec.recommendation)
            if rec.details:
                pdf.set_font("Helvetica", "", 9)
                pdf.safe_multi_cell(0, 4, rec.details)
                pdf.ln(2)
        pdf.ln(3)

    # --- Red Flags ---
    if ps.red_flags_for_patient:
        pdf.section_title("When to Seek Urgent Care")
        pdf.set_text_color(180, 0, 0)
        for rf in ps.red_flags_for_patient:
            pdf.set_font("Helvetica", "B", 10)
            pdf.safe_multi_cell(0, 5, f"  {rf.warning}")
            pdf.ln(2)
        pdf.set_text_color(0, 0, 0)
        pdf.ln(3)

    # --- Questions & Answers ---
    if ps.questions_and_answers:
        pdf.section_title("Questions & Answers from Your Visit")
        for qa in ps.questions_and_answers:
            pdf.set_font("Helvetica", "B", 10)
            pdf.safe_multi_cell(0, 5, f"Q: {qa.question}")
            pdf.set_font("Helvetica", "", 10)
            pdf.safe_multi_cell(0, 5, f"A: {qa.answer}")
            pdf.ln(3)

    # --- Optional SOAP Note ---
    if include_soap and visit_data.clinician_note:
        pdf.add_page()
        cn = visit_data.clinician_note
        soap = cn.soap_note

        pdf.section_title("SOAP Note (Clinician)")

        # Subjective
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(0, 6, "S:")
        pdf.ln(6)
        pdf.set_font("Helvetica", "", 9)
        for finding in soap.subjective.findings:
            pdf.safe_multi_cell(0, 4, f"- {finding}")
            pdf.ln(1)
        pdf.ln(4)

        # Objective
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(0, 6, "O:")
        pdf.ln(6)
        pdf.set_font("Helvetica", "", 9)
        if soap.objective.vital_signs:
            pdf.set_font("Helvetica", "B", 9)
            pdf.cell(0, 5, "Vital signs:")
            pdf.ln(5)
            pdf.set_font("Helvetica", "", 9)
            for v in soap.objective.vital_signs:
                pdf.safe_multi_cell(0, 4, f"- {v}")
                pdf.ln(1)
        if soap.objective.physical_exam:
            pdf.set_font("Helvetica", "B", 9)
            pdf.cell(0, 5, "Physical Examination:")
            pdf.ln(5)
            pdf.set_font("Helvetica", "", 9)
            for pe in soap.objective.physical_exam:
                pdf.safe_multi_cell(0, 4, f"- {pe}")
                pdf.ln(1)
        if soap.objective.mental_state_exam:
            pdf.set_font("Helvetica", "B", 9)
            pdf.cell(0, 5, "Mental state examination:")
            pdf.ln(5)
            pdf.set_font("Helvetica", "", 9)
            for mse in soap.objective.mental_state_exam:
                pdf.safe_multi_cell(0, 4, f"- {mse}")
                pdf.ln(1)
        if soap.objective.lab_results:
            pdf.set_font("Helvetica", "B", 9)
            pdf.cell(0, 5, "Lab results:")
            pdf.ln(5)
            pdf.set_font("Helvetica", "", 9)
            for lab in soap.objective.lab_results:
                pdf.safe_multi_cell(0, 4, f"- {lab}")
                pdf.ln(1)
        pdf.ln(4)

        # Assessment
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(0, 6, "A:")
        pdf.ln(6)
        pdf.set_font("Helvetica", "", 9)
        for finding in soap.assessment.findings:
            pdf.safe_multi_cell(0, 4, f"- {finding}")
            pdf.ln(1)
        pdf.ln(4)

        # Plan
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(0, 6, "P:")
        pdf.ln(6)
        pdf.set_font("Helvetica", "", 9)
        for finding in soap.plan.findings:
            pdf.safe_multi_cell(0, 4, f"- {finding}")
            pdf.ln(1)
        pdf.ln(4)

        # Problem list
        if cn.problem_list:
            pdf.set_font("Helvetica", "B", 10)
            pdf.cell(0, 6, "Problem List:")
            pdf.ln(6)
            pdf.set_font("Helvetica", "", 9)
            for prob in cn.problem_list:
                pdf.cell(0, 5, f"  - {prob}")
                pdf.ln(5)

    pdf.output(output_path)
    logger.info(f"PDF generated: {output_path}")
    return output_path
