"""PDF export using fpdf2 for After Visit Summary generation."""

import os
import logging
from datetime import datetime

from fpdf import FPDF

from models.schemas import VisitRecord

logger = logging.getLogger(__name__)


class MedSiftPDF(FPDF):
    """Custom PDF class with MedSift AI branding."""

    def header(self):
        """Add header to each page."""
        self.set_font("Helvetica", "B", 14)
        self.cell(0, 10, "MedSift AI", align="L")
        self.ln(6)
        self.set_font("Helvetica", "", 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 5, "After Visit Summary", align="L")
        self.set_text_color(0, 0, 0)
        self.ln(8)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(5)

    def footer(self):
        """Add footer with page number."""
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}}", align="C")

    def section_title(self, title: str):
        """Add a section title."""
        self.set_font("Helvetica", "B", 12)
        self.set_fill_color(240, 240, 240)
        self.cell(0, 8, f"  {title}", fill=True)
        self.ln(10)
        self.set_font("Helvetica", "", 10)

    def add_paragraph(self, text: str):
        """Add a paragraph of text."""
        self.set_font("Helvetica", "", 10)
        self.multi_cell(0, 5, text)
        self.ln(3)

    def add_table_row(self, cells: list[str], widths: list[int], bold: bool = False):
        """Add a table row."""
        style = "B" if bold else ""
        self.set_font("Helvetica", style, 9)
        max_height = 5
        for i, (cell, width) in enumerate(zip(cells, widths)):
            self.cell(width, max_height, cell, border=1)
        self.ln(max_height)


def generate_after_visit_summary(
    visit_data: VisitRecord,
    output_path: str,
    include_soap: bool = False,
) -> str:
    """Generate an After Visit Summary PDF.

    Args:
        visit_data: Complete visit record.
        output_path: Path to save the PDF.
        include_soap: Whether to include SOAP note (clinician export).

    Returns:
        The output file path.
    """
    os.makedirs(os.path.dirname(output_path) if os.path.dirname(output_path) else ".", exist_ok=True)

    pdf = MedSiftPDF()
    pdf.alias_nb_pages()
    pdf.set_auto_page_break(auto=True, margin=20)

    # --- Page 1: Header & Disclaimer ---
    pdf.add_page()

    # Visit info
    pdf.set_font("Helvetica", "", 10)
    visit_date_str = visit_data.visit_date.isoformat() if visit_data.visit_date else "N/A"
    pdf.cell(0, 6, f"Visit Date: {visit_date_str}    |    Visit Type: {visit_data.visit_type or 'N/A'}")
    pdf.ln(10)

    # Disclaimer
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(180, 0, 0)
    pdf.multi_cell(0, 4,
        "DISCLAIMER: This summary was generated by AI from a recorded conversation. "
        "Please verify all information with your healthcare provider. "
        "This document does not constitute medical advice."
    )
    pdf.set_text_color(0, 0, 0)
    pdf.ln(5)

    ps = visit_data.patient_summary
    if not ps:
        pdf.add_paragraph("No patient summary data available.")
        pdf.output(output_path)
        return output_path

    # --- Visit Summary ---
    pdf.section_title("Visit Summary")
    pdf.add_paragraph(ps.visit_summary or "No summary available.")

    # --- Medications ---
    if ps.medications:
        pdf.section_title("Medications")
        widths = [40, 25, 30, 30, 55]
        pdf.add_table_row(["Medication", "Dose", "Frequency", "Duration", "Instructions"], widths, bold=True)
        for med in ps.medications:
            pdf.add_table_row(
                [med.name, med.dose, med.frequency, med.duration, med.instructions],
                widths,
            )
        pdf.ln(5)

    # --- Tests Ordered ---
    if ps.tests_ordered:
        pdf.section_title("Tests Ordered")
        widths = [50, 70, 60]
        pdf.add_table_row(["Test", "Instructions", "Timeline"], widths, bold=True)
        for test in ps.tests_ordered:
            pdf.add_table_row(
                [test.test_name, test.instructions, test.timeline],
                widths,
            )
        pdf.ln(5)

    # --- Follow-Up Plan ---
    if ps.follow_up_plan:
        pdf.section_title("Follow-Up Plan")
        for fu in ps.follow_up_plan:
            pdf.set_font("Helvetica", "", 10)
            pdf.cell(5, 5, chr(9744))  # Checkbox character
            pdf.cell(0, 5, f"  {fu.action} - {fu.date_or_timeline}")
            pdf.ln(6)
        pdf.ln(3)

    # --- Lifestyle Recommendations ---
    if ps.lifestyle_recommendations:
        pdf.section_title("Lifestyle Recommendations")
        for rec in ps.lifestyle_recommendations:
            pdf.set_font("Helvetica", "B", 10)
            pdf.cell(0, 5, f"  {rec.recommendation}")
            pdf.ln(5)
            if rec.details:
                pdf.set_font("Helvetica", "", 9)
                pdf.cell(10)
                pdf.multi_cell(0, 4, rec.details)
                pdf.ln(2)
        pdf.ln(3)

    # --- Red Flags ---
    if ps.red_flags_for_patient:
        pdf.section_title("When to Seek Urgent Care")
        pdf.set_text_color(180, 0, 0)
        for rf in ps.red_flags_for_patient:
            pdf.set_font("Helvetica", "B", 10)
            pdf.multi_cell(0, 5, f"  {rf.warning}")
            pdf.ln(2)
        pdf.set_text_color(0, 0, 0)
        pdf.ln(3)

    # --- Questions & Answers ---
    if ps.questions_and_answers:
        pdf.section_title("Questions & Answers from Your Visit")
        for qa in ps.questions_and_answers:
            pdf.set_font("Helvetica", "B", 10)
            pdf.multi_cell(0, 5, f"Q: {qa.question}")
            pdf.set_font("Helvetica", "", 10)
            pdf.multi_cell(0, 5, f"A: {qa.answer}")
            pdf.ln(3)

    # --- Risk Assessment ---
    ra = visit_data.risk_assessment
    if ra:
        pdf.section_title("Risk Assessment")
        color_map = {"low": (0, 150, 0), "medium": (200, 150, 0), "high": (200, 0, 0)}
        color = color_map.get(ra.risk_level, (0, 0, 0))
        pdf.set_text_color(*color)
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(0, 8, f"Risk Level: {ra.risk_level.upper()} (Score: {ra.risk_score}/100)")
        pdf.set_text_color(0, 0, 0)
        pdf.ln(10)
        pdf.set_font("Helvetica", "I", 8)
        pdf.multi_cell(0, 4, ra.disclaimer)
        pdf.ln(5)

    # --- Optional SOAP Note ---
    if include_soap and visit_data.clinician_note:
        pdf.add_page()
        cn = visit_data.clinician_note
        soap = cn.soap_note

        pdf.section_title("SOAP Note (Clinician)")

        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(0, 6, "Subjective:")
        pdf.ln(6)
        pdf.set_font("Helvetica", "", 9)
        pdf.multi_cell(0, 4, f"CC: {soap.subjective.chief_complaint}")
        pdf.ln(2)
        pdf.multi_cell(0, 4, f"HPI: {soap.subjective.history_of_present_illness}")
        pdf.ln(2)
        pdf.multi_cell(0, 4, f"ROS: {soap.subjective.review_of_systems}")
        pdf.ln(4)

        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(0, 6, "Objective:")
        pdf.ln(6)
        pdf.set_font("Helvetica", "", 9)
        pdf.multi_cell(0, 4, f"Vitals: {soap.objective.vitals}")
        pdf.ln(2)
        pdf.multi_cell(0, 4, f"PE: {soap.objective.physical_exam_findings}")
        pdf.ln(4)

        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(0, 6, "Assessment:")
        pdf.ln(6)
        pdf.set_font("Helvetica", "", 9)
        pdf.multi_cell(0, 4, f"Diagnoses: {', '.join(soap.assessment.diagnoses)}")
        pdf.ln(2)
        pdf.multi_cell(0, 4, f"Impression: {soap.assessment.clinical_impression}")
        pdf.ln(4)

        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(0, 6, "Plan:")
        pdf.ln(6)
        pdf.set_font("Helvetica", "", 9)
        if soap.plan.medications:
            pdf.multi_cell(0, 4, f"Medications: {', '.join(soap.plan.medications)}")
            pdf.ln(2)
        if soap.plan.tests_ordered:
            pdf.multi_cell(0, 4, f"Tests: {', '.join(soap.plan.tests_ordered)}")
            pdf.ln(2)
        if soap.plan.referrals:
            pdf.multi_cell(0, 4, f"Referrals: {', '.join(soap.plan.referrals)}")
            pdf.ln(2)
        pdf.multi_cell(0, 4, f"Follow-up: {soap.plan.follow_up}")
        pdf.ln(4)

        # Problem list
        if cn.problem_list:
            pdf.set_font("Helvetica", "B", 10)
            pdf.cell(0, 6, "Problem List:")
            pdf.ln(6)
            pdf.set_font("Helvetica", "", 9)
            for prob in cn.problem_list:
                pdf.cell(0, 5, f"  - {prob}")
                pdf.ln(5)

    pdf.output(output_path)
    logger.info(f"PDF generated: {output_path}")
    return output_path
